# Generated by Django 3.1.2 on 2020-12-07 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_auto_20201208_0258'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeProportion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_point', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('exam1', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('exam2', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('experiment', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('contest', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('attendance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_point', models.IntegerField(null=True)),
                ('exam1_point', models.IntegerField(null=True)),
                ('exam2_point', models.IntegerField(null=True)),
                ('experiment_point', models.IntegerField(null=True)),
                ('contest_point', models.IntegerField(null=True)),
                ('attendance_point', models.IntegerField(null=True)),
                ('bonus_point', models.IntegerField(null=True)),
                ('total_point', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'unique_together': {('student_id', 'course_id')},
            },
        ),
    ]
