# Generated by Django 3.1.2 on 2020-12-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeproportion',
            name='assignment_point',
        ),
        migrations.RemoveField(
            model_name='gradeproportion',
            name='id',
        ),
        migrations.AddField(
            model_name='gradeproportion',
            name='assignment',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gradeproportion',
            name='attendance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gradeproportion',
            name='contest',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gradeproportion',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gradeproportion',
            name='exam1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gradeproportion',
            name='exam2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gradeproportion',
            name='experiment',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
