# Generated by Django 3.1.2 on 2020-12-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20201211_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
