FROM python:3
ENV PYTHONUNBUFFERED=1

RUN mkdir /code
COPY ./requirements/dev.txt /code

# Use tuna mirrors
RUN pip install pip -U
RUN pip config set global.index-url https://mirrors.cloud.tencent.com/pypi/simple

RUN pip install -r /code/dev.txt

WORKDIR /code/catfood
