FROM python:3
ENV PYTHONUNBUFFERED=1

ENV HOME=/home/code
WORKDIR /code/catfood

RUN mkdir -p /home/code
RUN mkdir -p /code/catfood

# Install pypi packages
COPY ./requirements/dev.txt /code
RUN pip install pip -U
RUN pip config set global.index-url https://mirrors.cloud.tencent.com/pypi/simple
RUN pip install -r /code/dev.txt

# Prepare to use non-root
## root:mypasswd
## code:mypasswd
RUN echo 'root:mypasswd' | chpasswd
COPY ./webscript/ /code/script

ENTRYPOINT [ "/code/script/entrypoint.sh" ]
CMD []
