rm -rf catfood/bulletin/migrations
rm -rf catfood/contest/migrations
rm -rf catfood/course_database/migrations
rm -rf catfood/course/migrations
rm -rf catfood/grade/migrations
rm -rf catfood/user/migrations
rm -rf catfood/experiment/migrations
rm -rf catfood/lecture/migrations
rm -rf catfood/quiz/migrations
rm -rf catfood/class/migrations
rm -rf .persistence 
echo "delete finished"
