# Generated by Django 3.1.2 on 2020-12-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201206_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='official_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
