# Generated by Django 3.1.2 on 2020-12-19 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('homework_student_grade', models.IntegerField()),
                ('homework_teachers_comments', models.CharField(max_length=2048)),
                ('homework_is_grade_available_to_students', models.BooleanField(default=False)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseChapterDescrption',
            fields=[
                ('course_chapter_description_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('course_chapter_id', models.IntegerField()),
                ('course_chapter_title', models.CharField(max_length=64)),
                ('course_chapter_mooc_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homework_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('homework_creator', models.IntegerField()),
                ('homework_description', models.CharField(max_length=1024)),
                ('homework_attachment_link', models.CharField(max_length=200)),
                ('homework_start_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('file_homework_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_uploader', models.IntegerField()),
                ('file_usage', models.CharField(choices=[('Experiment', 'Experiment'), ('Lecture', 'Lecture')], max_length=100)),
                ('file_timestamp', models.DateField(auto_now=True)),
                ('file_link', models.CharField(max_length=200)),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.homework')),
            ],
        ),
    ]
