# Generated by Django 3.1.2 on 2020-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChapterDescrption',
            fields=[
                ('course_chapter_description_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='HomeworkFile',
            name='file_uploader',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='Homework',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='Homework',
            name='homework_creator',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='HomeworkScore',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
