# Generated by Django 3.1.2 on 2020-12-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkscore',
            name='homework_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, to='lecture.homework'),
            preserve_default=False,
        ),
    ]
