# Generated by Django 3.1.2 on 2020-12-14 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapterdescrption',
            name='course_chapter_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursechapterdescrption',
            name='course_chapter_mooc_link',
            field=models.CharField(default='http://buyssd.com', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursechapterdescrption',
            name='course_chapter_title',
            field=models.CharField(default='dfsajn', max_length=64),
            preserve_default=False,
        ),
    ]
