# Generated by Django 3.1.2 on 2020-12-09 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_auto_20201209_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='HomeworkScore',
            name='homework_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Homework'),
        ),
    ]
