# Generated by Django 3.1.2 on 2020-12-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_remove_homeworkfile_file_usage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeworkfile',
            old_name='file_link',
            new_name='file_token',
        ),
    ]
