# Generated by Django 3.1.2 on 2020-12-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_auto_20201209_1924'),
    ]

    operations = [
    ]
