# Generated by Django 3.1.2 on 2020-12-09 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20201209_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeworkscore',
            options={'managed': False},
        ),
    ]
