<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-12-14 13:09
=======
# Generated by Django 3.1.2 on 2020-12-16 11:14
>>>>>>> 20dbdb73ae5f71a19d83b02cb510a91a7dc2fb40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('announcement_title', models.CharField(max_length=50)),
                ('announcement_contents', models.CharField(max_length=1024, null=True)),
                ('announcement_is_pinned', models.BooleanField(default=False)),
                ('announcement_publish_time', models.DateTimeField(auto_now=True)),
                ('announcement_last_update_time', models.DateTimeField(auto_now=True)),
                ('announcement_sender_id', models.IntegerField()),
            ],
        ),
    ]
