# Generated by Django 3.1.2 on 2020-11-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement_title', models.CharField(max_length=50)),
                ('announcement_contents', models.CharField(max_length=200, null=True)),
                ('announcement_is_sticky_on_top', models.BooleanField(default=True)),
                ('announcement_timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
