# Generated by Django 3.1.2 on 2020-12-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0003_announcement_announcement_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='announcement_sender_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='course_id',
            field=models.IntegerField(),
        ),
    ]
