# Generated by Django 3.1.2 on 2020-11-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_creator_school_id', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=200, null=True)),
                ('course_credit', models.IntegerField(default=0)),
                ('course_type', models.BooleanField(default=True)),
                ('course_start_timestamp', models.DateTimeField()),
                ('course_end_timestamp', models.DateTimeField()),
                ('course_avatar', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField(default=2)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.course')),
            ],
        ),
    ]
