# Generated by Django 3.1.2 on 2020-12-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Single'), (1, 'Multiple')], default=0),
        ),
        migrations.AlterField(
            model_name='quizsubmission',
            name='question_type',
            field=models.IntegerField(choices=[(0, 'Single'), (1, 'Multiple')], default=0),
        ),
    ]
