<<<<<<< HEAD
# Generated by Django 3.1.2 on 2020-12-14 13:09
=======
# Generated by Django 3.1.2 on 2020-12-16 11:14
>>>>>>> 20dbdb73ae5f71a19d83b02cb510a91a7dc2fb40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_creator_school_id', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=512, null=True)),
                ('course_credit', models.IntegerField(default=0)),
                ('course_study_time_needed', models.IntegerField(default=0)),
                ('course_type', models.CharField(max_length=20)),
                ('course_start_time', models.DateTimeField()),
                ('course_end_time', models.DateTimeField()),
                ('course_avatar', models.CharField(max_length=100)),
                ('course_is_score_public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('course_teach_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
