# Generated by Django 3.1.2 on 2020-12-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20201215_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_is_score_public',
            field=models.BooleanField(default=False),
        ),
    ]
