# Generated by Django 3.1.2 on 2020-12-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDocument',
            fields=[
                ('file_course_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_usage', models.CharField(max_length=100)),
                ('file_timestamp', models.DateTimeField(auto_now=True)),
                ('file_comment', models.CharField(max_length=1024)),
                ('file_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentCaseDatabase',
            fields=[
                ('experiment_case_id', models.AutoField(primary_key=True, serialize=False)),
                ('experiment_name', models.CharField(max_length=50)),
                ('experiment_case_name', models.CharField(max_length=50)),
                ('experiment_case_description', models.CharField(max_length=1024, null=True)),
                ('experiment_case_file_token', models.CharField(max_length=256)),
                ('answer_file_token', models.CharField(max_length=256)),
                ('case_created_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_chapter', models.IntegerField()),
                ('question_content', models.CharField(max_length=100)),
                ('question_choice_a_content', models.CharField(max_length=256)),
                ('question_choice_b_content', models.CharField(max_length=256)),
                ('question_choice_c_content', models.CharField(max_length=256)),
                ('question_choice_d_content', models.CharField(max_length=256)),
                ('question_answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SingleChoiceQuestion',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_chapter', models.IntegerField()),
                ('question_content', models.CharField(max_length=100)),
                ('question_choice_a_content', models.CharField(max_length=256)),
                ('question_choice_b_content', models.CharField(max_length=256)),
                ('question_choice_c_content', models.CharField(max_length=256)),
                ('question_choice_d_content', models.CharField(max_length=256)),
                ('question_answer', models.CharField(max_length=20)),
            ],
        ),
    ]
