# Generated by Django 3.1.2 on 2020-12-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choicemultiplequestiondatabase',
            name='question_chapter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choicesinglequestiondatabase',
            name='question_chapter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
