# Generated by Django 3.1.2 on 2020-12-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_database', '0002_auto_20201208_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentcasedatabase',
            name='component_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
