# Generated by Django 3.1.2 on 2020-12-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_database', '0002_auto_20201215_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentDocument',
            fields=[
                ('file_course_document_id', models.AutoField(primary_key=True, serialize=False)),
                ('experiment_id', models.IntegerField()),
                ('file_display_name', models.CharField(max_length=1024)),
                ('file_comment', models.CharField(max_length=1024)),
                ('file_create_timestamp', models.DateTimeField(auto_now=True)),
                ('file_update_timestamp', models.DateTimeField(auto_now=True)),
                ('file_uploader', models.IntegerField()),
                ('file_token', models.CharField(max_length=200)),
            ],
        ),
    ]
