# Generated by Django 3.1.2 on 2020-12-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_database', '0004_auto_20201209_1912'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='choiceMultipleQuestionDatabase',
            new_name='MultipleChoiceQuestion',
        ),
        migrations.RenameModel(
            old_name='choiceSingleQuestionDatabase',
            new_name='SingleChoiceQuestion',
        ),
    ]
