# Generated by Django 3.1.2 on 2020-12-14 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AddField(
            model_name='contestsubmission',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestquestion',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AddField(
            model_name='contest',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AddField(
            model_name='contest',
            name='publisher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendcontest',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest'),
        ),
        migrations.AddField(
            model_name='attendcontest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='contestsubmission',
            unique_together={('user_id', 'contest_id', 'question_id', 'question_type')},
        ),
        migrations.AlterUniqueTogether(
            name='contestquestion',
            unique_together={('contest_id', 'question_id', 'question_type')},
        ),
        migrations.AlterUniqueTogether(
            name='attendcontest',
            unique_together={('user_id', 'contest_id')},
        ),
    ]
