# Generated by Django 3.1.2 on 2020-12-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_auto_20201219_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_tag',
            field=models.IntegerField(default=0),
        ),
    ]
