# Generated by Django 3.1.2 on 2020-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20201223_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendcontest',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
